# 3. Fibonacci Sequence
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Pseudocode
number_list = []
for number in range(1, 101):
    if (number % 2 == 0):
        number_list.append(number)
print(number_list)
